import { describe, expect, it } from 'vitest';

import { parseNzb } from '../src/parse.ts';

function nzb(body: string): string {
  return `<nzb xmlns="http://www.newzbin.com/DTD/2003/nzb">${body}</nzb>`;
}

function file(subject: string, groups: readonly string[], segments: string): string {
  const escaped = subject.replaceAll('&', '&amp;').replaceAll('"', '&quot;');
  return `<file poster="p@x.invalid" date="1000000000" subject="${escaped}">
    <groups>${groups.map((g) => `<group>${g}</group>`).join('')}</groups>
    <segments>${segments}</segments>
  </file>`;
}

describe('parseNzb head metadata', () => {
  it('collects every meta entry, preserving duplicates and unknown types', () => {
    const parsed = parseNzb(
      nzb(`<head>
        <meta type="title">A Release</meta>
        <meta type="password">hunter2</meta>
        <meta type="tag">one</meta>
        <meta type="tag">two</meta>
        <meta type="x-indexer-private">whatever</meta>
      </head>`),
    );

    expect(parsed.meta).toEqual([
      { type: 'title', value: 'A Release' },
      { type: 'password', value: 'hunter2' },
      { type: 'tag', value: 'one' },
      { type: 'tag', value: 'two' },
      { type: 'x-indexer-private', value: 'whatever' },
    ]);
  });

  it('returns an empty meta list when there is no head block', () => {
    expect(parseNzb(nzb(''))).toEqual({ meta: [], files: [], groups: [] });
  });
});

describe('parseNzb derived fields', () => {
  it('sums encoded bytes across segments', () => {
    const parsed = parseNzb(
      nzb(
        file(
          '"a.bin" yEnc (1/2)',
          ['alt.binaries.misc'],
          [
            '<segment bytes="100" number="1">a@x</segment>',
            '<segment bytes="25" number="2">b@x</segment>',
          ].join(''),
        ),
      ),
    );

    expect(parsed.files[0]?.totalEncodedBytes).toBe(125);
  });

  it('sorts segments by number and reports a contiguous 1..n run', () => {
    const parsed = parseNzb(
      nzb(
        file(
          '"a.bin" yEnc (1/3)',
          ['alt.binaries.misc'],
          [
            '<segment bytes="1" number="3">c@x</segment>',
            '<segment bytes="1" number="1">a@x</segment>',
            '<segment bytes="1" number="2">b@x</segment>',
          ].join(''),
        ),
      ),
    );

    expect(parsed.files[0]?.segments.map((s) => s.number)).toEqual([1, 2, 3]);
    expect(parsed.files[0]?.contiguous).toBe(true);
  });

  it('flags a gap in the segment numbering', () => {
    const parsed = parseNzb(
      nzb(
        file(
          '"a.bin" yEnc (1/3)',
          ['alt.binaries.misc'],
          [
            '<segment bytes="1" number="1">a@x</segment>',
            '<segment bytes="1" number="3">c@x</segment>',
          ].join(''),
        ),
      ),
    );

    expect(parsed.files[0]?.contiguous).toBe(false);
  });

  it('deduplicates the group union across files while keeping per-file groups', () => {
    const parsed = parseNzb(
      nzb(
        file(
          '"a.bin" yEnc (1/1)',
          ['alt.binaries.misc', 'alt.binaries.test'],
          '<segment bytes="1" number="1">a@x</segment>',
        ) +
          file(
            '"b.bin" yEnc (1/1)',
            ['alt.binaries.test', 'alt.binaries.multimedia'],
            '<segment bytes="1" number="1">b@x</segment>',
          ),
      ),
    );

    expect(parsed.groups).toEqual([
      'alt.binaries.misc',
      'alt.binaries.test',
      'alt.binaries.multimedia',
    ]);
    expect(parsed.files[1]?.groups).toEqual(['alt.binaries.test', 'alt.binaries.multimedia']);
  });

  it('strips angle brackets a poster wrongly left on a Message-ID', () => {
    const parsed = parseNzb(
      nzb(
        file(
          '"a.bin" yEnc (1/1)',
          ['alt.binaries.misc'],
          '<segment bytes="1" number="1">&lt;abc@news.example.com&gt;</segment>',
        ),
      ),
    );

    expect(parsed.files[0]?.segments[0]?.messageId).toBe('abc@news.example.com');
  });
});

describe('parseNzb document prologue and trivia', () => {
  it('skips the XML declaration, DOCTYPE, and comments', () => {
    const parsed = parseNzb(
      `<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE nzb PUBLIC "-//newzBin//DTD NZB 1.1//EN" "http://www.newzbin.com/DTD/nzb/nzb-1.1.dtd">
<!-- generated by something -->
${nzb(`<!-- inner comment -->${file('"a.bin" yEnc (1/1)', ['alt.binaries.misc'], '<segment bytes="1" number="1">a@x</segment>')}`)}`,
    );

    expect(parsed.files).toHaveLength(1);
    expect(parsed.files[0]?.segments[0]?.messageId).toBe('a@x');
  });

  it('reads a Message-ID out of a CDATA section', () => {
    const parsed = parseNzb(
      nzb(
        file(
          '"a.bin" yEnc (1/1)',
          ['alt.binaries.misc'],
          '<segment bytes="1" number="1"><![CDATA[weird&id@news.example.com]]></segment>',
        ),
      ),
    );

    expect(parsed.files[0]?.segments[0]?.messageId).toBe('weird&id@news.example.com');
  });

  it('accepts namespace-prefixed element names', () => {
    const parsed = parseNzb(
      `<n:nzb xmlns:n="http://www.newzbin.com/DTD/2003/nzb">
        <n:file poster="p@x.invalid" date="1000000000" subject="&quot;a.bin&quot; yEnc (1/1)">
          <n:groups><n:group>alt.binaries.misc</n:group></n:groups>
          <n:segments><n:segment bytes="1" number="1">a@x</n:segment></n:segments>
        </n:file>
      </n:nzb>`,
    );

    expect(parsed.files[0]?.subjectHints.name).toBe('a.bin');
    expect(parsed.files[0]?.groups).toEqual(['alt.binaries.misc']);
  });
});

describe('parseNzb rejects malformed input', () => {
  it('rejects a document with no nzb root', () => {
    expect(() => parseNzb('<rss><channel/></rss>')).toThrow(/no <nzb> root element/u);
  });

  it('rejects mismatched closing tags', () => {
    expect(() => parseNzb(nzb('<head><meta type="title">x</head></meta>'))).toThrow(
      /does not match/u,
    );
  });

  it('rejects an unclosed element', () => {
    expect(() => parseNzb('<nzb><head>')).toThrow(/unclosed <head> element/u);
  });

  it('rejects a file with no date attribute', () => {
    expect(() =>
      parseNzb(nzb('<file poster="p@x.invalid" subject="x"><groups/><segments/></file>')),
    ).toThrow(/missing the "date" attribute/u);
  });

  it('rejects a non-integer segment byte count', () => {
    expect(() =>
      parseNzb(
        nzb(
          file(
            '"a.bin" yEnc (1/1)',
            ['alt.binaries.misc'],
            '<segment bytes="lots" number="1">a@x</segment>',
          ),
        ),
      ),
    ).toThrow(/attribute "bytes" is not an integer/u);
  });

  it('rejects an unrecognized entity rather than passing it through', () => {
    expect(() =>
      parseNzb(
        nzb(
          file(
            '"a.bin" yEnc (1/1)',
            ['alt.binaries.misc'],
            '<segment bytes="1" number="1">a&nbsp;b@x</segment>',
          ),
        ),
      ),
    ).toThrow(/unrecognized entity reference "&nbsp;"/u);
  });

  it('rejects a duplicate attribute instead of silently picking one', () => {
    expect(() =>
      parseNzb(
        nzb(
          `<file poster="p@x.invalid" date="1000000000" date="2000000000" subject="x">
            <groups><group>alt.binaries.misc</group></groups>
            <segments><segment bytes="1" number="1">a@x</segment></segments>
          </file>`,
        ),
      ),
    ).toThrow(/duplicate attribute "date"/u);
  });
});
